# Generated by Django 3.2.5 on 2021-07-20 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_businessdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessdetails',
            old_name='email',
            new_name='business_category',
        ),
        migrations.RemoveField(
            model_name='businessdetails',
            name='date_created',
        ),
    ]
